# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Gank' do
pod 'SwiftyJSON'
pod 'Kingfisher', '~> 2.4'
end

target 'GankTests' do

end

